id: I4BF80FC6
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:17:15.758971+00:00
last_modified: 2022-12-14 18:17:15.758978+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2019-08-01T19:01:17.164Z'
  creationid: celso
  eft-text-id: UT22084-064-001
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_231-The_Jewel_Cloud-v1
bases:
  764A:
    source_metadata: null
    order: 1
    base_file: 764A.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
